version: '3.1'
services:
  mongodb:
    container_name: aeswolf_mongodb
    image: mongo
    restart: on-failure:5
    ports:
      - 27007:27017
    environment:
      MONGO_INITDB_DATABASE: aeswolf_api
    volumes:
      - aeswolfVolume:/data/db

volumes:
  aeswolfVolume:
    name: aeswolf_MongoDB
